apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-uwsgi
  name: helloworld-uwsgi
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: helloworld-uwsgi
  type: LoadBalancer
